#!/command/with-contenv sh
# Create SVN configuration

# /data/subversion: persistent storage for subversion configuration
if [ ! -d /data/subversion ]; then
    mkdir -p /data/subversion
fi

if [ ! -e /etc/subversion ]; then
    ln -s /data/subversion /etc/subversion
fi

# copy default configuration if not yet existing e.g. initial start
if [ ! -f /data/subversion/passwd ]; then
    cp /opt/default_data/subversion/passwd /data/subversion/passwd
fi

if [ ! -f /data/subversion/subversion-access-control ]; then
    cp /opt/default_data/subversion/subversion-access-control /data/subversion/subversion-access-control
fi

chown -R svn:svnusers /data/subversion
