#!/command/with-contenv sh
# Create SVN configuration

# /config/subversion: persistent storage for subversion configuration
if [ ! -d /config/subversion ]; then
  install -d -o abc -g abc /config/subversion
fi

lsiown -R abc:abc /config/subversion

if [ ! -e /etc/subversion ]; then
  ln -s /config/subversion /etc/subversion
fi

# copy default configuration if not yet existing e.g. initial start
if [ ! -f /config/subversion/passwd ]; then
  install -o abc -g abc /defaults/subversion/passwd /config/subversion/passwd
fi

if [ ! -f /config/subversion/subversion-access-control ]; then
  install -o abc -g abc /defaults/subversion/subversion-access-control /config/subversion/subversion-access-control
fi