#!/command/with-contenv sh

# From https://github.com/smebberson/docker-alpine/tree/master/alpine-apache

# avoid 'already pid is running' error
rm -f /run/apache2/httpd.pid

export HOME=$(realpath ~abc)
exec s6-setuidgid abc \
  /usr/sbin/apachectl -DFOREGROUND;