name: Update Docker Hub Description
on:
  push:
    branches:
      - 'master'
    paths:
      - 'README.md'
      - '.github/workflows/docker-description.yml'

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: ${{ secrets.DOCKERHUB_USERNAME }}/svn-docker
        short-description: ${{ github.event.repository.description }}
        enable-url-completion: true